### ISSUE TITLE
'class EEPROMClass' has no member named 'put'

### ISSUE THREAD

**Issue by FabianBremer** [xfjx/TonUINO#102]
Hallo zusammen,

leider bekomme ich beim Überprüfen/Komplimieren die Fehlermeldung:

'class EEPROMClass' has no member named 'put'

 Hat jemand eine Idee wie ich das Problem fixen kann?

Vielen Dank im Voraus.

**Comment by danizwam** [comment]
Schau mal hier: https://discourse.voss.earth/t/bekomme-keine-verbindung-zum-aio/7961/4

Da wurde das Thema schon behandelt.

**Comment by seisfeld** [comment]
Danke für den Hinweis auf das Forum. Dort sind solche Fragen wirklich besser aufgehoben. Ansonsten: Für die AiO bitte auch die AiO kompatible Software verwenden.

https://github.com/tonuino/TonUINO/tree/All-in-One
