### ISSUE TITLE
Logo Design for TonUINO

### ISSUE THREAD

**Issue by zuurw** [xfjx/TonUINO#11]
Hi, my name is Zuur W. I'm a graphic designer and I'd like to collaborate on your open source project and propose free logo/icon design for your project. If it's something you're interested in, please, let me know!
Best Regards
Zuur

**Comment by xfjx** [comment]
Hi Zuur, right now I am looking for a somehow professional logo so it would be great if you would like to help me with that.

We have already discussed the logo idea within our community and we thought a simple "TonUINO" with the last O as a speaker symbol would be good.

What would also be great would be the "Ton" with some kind of music notes (as "Ton" stands for note in german) and the UINIO somehow related to arduino or robot or something.

But of cause you can also suggest something completely different if you have something in mind.

Thank you very much in advance. May I ask how you found the project? Do you know the official page https://voss.earth/tonuino

**Comment by xfjx** [comment]
the three (arcade) push buttons would also be nice to be included in the logo somehow

**Comment by zuurw** [comment]
Hi @xfjx thanks for the informations, I wil start to create some design for you.

Greetings!

**Comment by xfjx** [comment]
I really like this one a lot (the right one). Maybe you can take this as a starting point.

![d8d8bf4eb333e220960f7c0cfc4e0a6f66074162_1_1332x1000](https://user-images.githubusercontent.com/10652613/48377161-50052a00-e6cd-11e8-8eae-2ca584c86235.jpeg)

An other one which was submitted by someone of the community is this one. Really playful.

![54d5c9667f9cc65a16f698039a4e247aea0004f2](https://user-images.githubusercontent.com/10652613/48377252-98bce300-e6cd-11e8-9b10-0041ebef53fe.png)

Of cause the are not finished yet. I'd love to have a simple one, but maybe still a little bit childish as the whole project is for children.

**Comment by xfjx** [comment]
Our community has created a new draft 

http://discourse.voss.earth/t/kurze-frage-wuerdet-ihr-ein-logo-auf-eure-box-kleben/66/34

Can you please try to take the last image in the thread as a reference. It is basically the one I posted before but with three buttons at the top

**Comment by zuurw** [comment]
This last one it´s really a good ideia I will pick that one has reference.

Cheers!!!

**Comment by zuurw** [comment]
Hi, this is my first design with some variations, see if you like it or not. I can make another one or make some changes to this one.

![tonuino](https://user-images.githubusercontent.com/40801473/48590390-3a933880-e937-11e8-8ec5-0a5e907f0c33.png)

**Comment by seisfeld** [comment]
I like the right ones. Left looks like a locomotive to me hehe. And from the right ones, the second and the fourth, were the first "o" ist not connected to the outline of the Box. Favorite currently is the bottom right. Good job so far!

**Comment by xfjx** [comment]
Wow, they look really nice already. Very modern and fresh!
I would love to have the logo look a bit more like a real speaker - the lower circle more in the middle of the box. And maybe an other one with the small o above the big one.
Please take the right one in the second row and the last row as a start for the next iterations.

Tank you very much in advance

**Comment by seisfeld** [comment]
Hey @zuurw,

did you make any progress? We are excited to see what you come up with!

Cheers
Stephan

**Comment by xfjx** [comment]
@zuurw are you still alive?

**Comment by seisfeld** [comment]
It's almost 3 months with no reply, therefore I'm closing this one now.
