### ISSUE TITLE
Anzahl Titel im Ordner nicht erkannt

### ISSUE THREAD

**Issue by hankman13** [xfjx/TonUINO#12]
Hallo,
ich habe eine Karte angelernt für den Hörbuchmodus und eine Karte für den Hörspielmodus.
Wenn ich nun die Hörbuchkarte Karte einlese wird im Serial-Monitor angezeigt:
`Com Error 255`
`0 Dateien in Ordner 1`
Und fängt an zuspielen, hört aber nach dem Track auf und spielt nicht den nächsten Track.
Mit den Tasten Up/Down komme ich aber weiter/zurück.

Wenn ich die Hörspielkarte einlese wird im Serial-Monitor angezeigt:
`Com Error 255`
`0 Dateien in Ordner 1`
Und es wird immer nur die erste Datei abgespielt.

Offensichtlich gibt es Probleme beim Ermitteln der Tracks im Ordner.

Eine Idee was die Ursache sein könnte?

Danke!

**Comment by kerhac** [comment]
Hallo @hankman13, 
`Com Error 255`  wird vom  `Mp3Notify OnError` geschmissen und ist lauf [DFMiniMp3.h](https://github.com/Makuna/DFMiniMp3/blob/master/src/DFMiniMp3.h#L37) ein `DfMp3_Error_General`. Nicht besonders vielsagend. Achte drauf das die mp3s richtig benannt sind, vielleicht liegt da der Fehler.

```
.
├── 01
│   ├── 001.mp3
│   ├── 002.mp3
│   └── 003.mp3
├── 02
│   ├── 001.mp3
│   ├── 002.mp3
│   └── 003.mp3
```

**Comment by seisfeld** [comment]
In hartnäckigen Fällen hilft es auch die Karte zu formatieren und komplett neu zu bespielen. Falls ein Mac verwendet wird mit dot_clean bereinigen vor dem aushängen (auch wichtig, nicht einfach die Karte abziehen). Der DFPlayer ist sehr pingelig was die Karte angeht. Ansonsten wie @hankman13 schon schrieb, auf die Ordner und die Dateinamen achten.

**Comment by hankman13** [comment]
Ich besorg mir mal eine andere SD-Karte. Hab die Karte schon unter Windows formatiert und neu bespielt und das selbe auch mal mit Ubuntu.
Grundsätzlich klappt ja die Wiedergabe der MP3s, nur die Anzahl der Dateien bekommt er nicht gelesen.
Vielleicht muss ich mal andere DPPlayer Module bestellen.

**Comment by JonLi80** [comment]
Mir wird derselbe Fehler angezeigt.
Com Error 255
0 Dateien in Ordner 1

Mit der + Taste spielt Tonuino den nächsten Track ab und speichert auch den Fortschritt im Hörbuchmodus. Bei erneutem auflegen der Karte wird auch beim letzten abgespielten Track fortgesetzt.
Ich habe auch schon verschiedene SD Karten ausprobiert. Folder/File Struktur ist wie verlangt \01\001.mp3

**Comment by JonLi80** [comment]
Mein Problem ist gelöst:

Tx(DFMiniPlayer)->D2(Arduino Nano) war fehlerhaft gesteckt.

**Comment by hankman13** [comment]
@JonLi80 , @seisfeld Danke euch, das war der Fehler.
