### ISSUE TITLE
Mp3 TTS Dateien erzeugen mit "create-soundfiles.sh"

### ISSUE THREAD

**Issue by JocB1** [xfjx/TonUINO#13]
Ich suche für etwas ähnliches (Hausautomatisierung) die Möglichkeit viele Mp3 Ansagen per skript zu erzeugen, so wie es hier vermutlich mit der Datei "create-soundfiles.sh" gemacht wird. 

Mich würde interssieren welche Programme benötigt werden um die Script Datei auszuführen.

**Comment by seisfeld** [comment]
So wie das Script momentan ist: say (MacOS X only), [sox](http://sox.sourceforge.net) und [lame](http://lame.sourceforge.net).

**Comment by JocB1** [comment]
Ok, say gibt es nur für MacOs... 
Gibt es evtl. eine Windows Alternative - jemand hat hier im Projekt wohl auch was mit Google gemacht.

**Comment by seisfeld** [comment]
Keine Ahnung ob es sowas für Windows gibt. Hast Du noch ein konkretes Problem mit der TonUINO Firmware? Dafür ist nämlich dieser Bereich hier. Alles andere kann gerne in unserer [community](https://discourse.voss.earth) diskutiert werden. Dort gibt es auch einen Thread der erklärt wie das mit Google usw. gemacht wurde.
