### ISSUE TITLE
Hörbuchmodus funktioniert im DEV branch nicht

### ISSUE THREAD

**Issue by dm82m** [xfjx/TonUINO#21]
Mit dem aktuellen DEV branch b99ca71a599d2c3cc7232a43fb3702ac179b39b8 funktioniert der Hörbuchmodus nicht. Die Karte kann angelernt werden und es wird auch gespeichert, beim Auflegen der Karten im Hörbuchmodus erfolgt aber keine Wiedergabe. Im Albummodus klappt es.

Wenn etwas anderes läuft und man die Karte die im Hörbuchmodus programmiert wurde auflegt, stoppt die Wiedergabe des vorherigen Albums - es erfolgt aber kein Ton.

**Comment by xfjx** [comment]
Kannst du wohl mal einen Auszug von der Konsole schicken?

**Comment by dm82m** [comment]
kann ich dazu einfach das mini usb kabel zusätzlich zur powerbank anschließen oder besser die powerbank abklemmen nud nur über mini usb betreiben?

**Comment by xfjx** [comment]
nur USB bitte - ich schaue aber gleich selber einmal

**Comment by dm82m** [comment]
`19:36:36.724 -> ⸮@⸮⸮⸮⸮⸮⸮⸮⸮⸮H⸮BF⸮E⸮⸮⸮⸮⸮⸮⸮⸮⸮Lԩb
19:36:38.149 ->  _____         _____ _____ _____ _____
19:36:38.149 -> |_   _|___ ___|  |  |     |   | |     |
19:36:38.149 ->   | | | . |   |  |  |-   -| | | |  |  |
19:36:38.149 ->   |_| |___|_|_|_____|_____|_|___|_____|
19:36:38.149 -> 
19:36:38.149 -> TonUINO Version 2.1
19:36:38.149 -> created by Thorsten Voß and licensed under GNU/GPL.
19:36:38.184 -> Information and contribution at https://tonuino.de.
19:36:38.184 -> 
19:36:38.184 -> === loadSettingsFromFlash()
19:36:38.184 -> Version: 1
19:36:38.184 -> Maximal Volume: 25
19:36:38.184 -> Minimal Volume: 5
19:36:38.184 -> Initial Volume: 10
19:36:38.184 -> EQ: 1
19:36:38.184 -> Locked: 0
19:36:38.184 -> Sleep Timer: 5
19:36:38.184 -> Inverted Volume Buttons: 1
19:36:38.184 -> === setstandbyTimer()
19:36:38.184 -> 300034
19:36:40.307 -> Firmware Version: 0x92 = v2.0
19:36:40.307 -> === playShortCut()
19:36:40.307 -> 3
19:36:40.307 -> === disablestandby()
19:36:40.420 -> 1 Dateien in Ordner 1
19:36:40.420 -> Einzel Modus -> eine Datei aus dem Odrdner abspielen
19:36:40.420 -> === disablestandby()
19:36:46.195 -> === nextTrack()
19:36:46.195 -> Einzel Modus aktiv -> Strom sparen
19:36:46.195 -> === setstandbyTimer()
19:36:46.233 -> 308052
19:36:46.697 -> Card UID: 19 2E 76 13
19:36:46.697 -> PICC type: MIFARE 1KB
19:36:46.697 -> Authenticating Classic using key A...
19:36:46.697 -> Reading data from block 4 ...
19:36:46.735 -> Data on Card :
19:36:46.735 ->  13 37 B3 47 02 04 05 00 00 00 00 00 00 00 00 00
19:36:46.735 -> 
19:36:46.735 -> === disablestandby()
19:36:46.844 -> 4 Dateien in Ordner 4
19:36:46.844 -> Hörbuch Modus -> kompletten Ordner spielen und Fortschritt merken
19:36:47.483 -> 
19:36:47.483 -> Com Error 6
`

**Comment by xfjx** [comment]
es scheint daran zu liegen, dass vorher bereits ein Hörbuch für den Ordner vorhanden war und dier Fortschritt bereits auf einen Track zeigt den es nicht im Ordner gibt.

Ich habe mal einen Fix hochgeladen - prüf den mal bitte.

**Comment by dm82m** [comment]
Funktioniert, Danke. Wobei es nicht an Altlasten gelegen haben kann, das war ein nagelneues Setup.
