### ISSUE TITLE
Party Mode Next Song buggy

### ISSUE THREAD

**Issue by Strandbummler** [xfjx/TonUINO#27]
Ich hab im Party Modus das Problem, dass öfter der Next-Button nicht funktioniert bzw. das Playback einfach angehalten wird. Wenn ich dann auf Play drücke wird der vorherige Song einfach neugestartet. Erst nach mehrmaligen drücken des Next-Buttons kommt irgendwann der nächste Song. Das passiert auch wenn die Box von selber den Track wechseln will. Soweit ich das sehe passiert das nur im Party Modus. Alle anderen Modi machen in der Hinsicht keine Probleme. Ich tippe mal auf ein Cue Problem?

**Comment by xfjx** [comment]
Hast du mal in die Konsole geschaut? Drückst du eventuell sehr schnell? Dann würdest du einen Com 6 oder Com 255 Fehler in der Konsole sehen. Wäre hilfreich wenn du das noch nachliefern würdest.

Und ganz wichtig: Stable 2.0x oder die DEV Version?

**Comment by Strandbummler** [comment]
Hey, leider spuckt die Konsole bei mir nur Zeichensalat aus, egal ob der Serielle Monitor in der Arduino IDE oder im Terminal. Gibts irgendwo eine Anleitung wie ich da brauchbare Logs rausbekomme?
Ich nutze die DEV Version. Und sehr schnell, ich glaube nicht, passiert oft schon bei einmaligem drücken. Und wie geschrieben passiert es auch beim automatischen weitergehen zum nächsten Song ohne mein zutun.

**Comment by seisfeld** [comment]
> leider spuckt die Konsole bei mir nur Zeichensalat aus

Hast du die Baudrate (unten im Konsolenfenster der IDE) auf 115200 eigestellt?

**Comment by Strandbummler** [comment]
Tatsächlich ein Com 6 Fehler, aber ich drücke die Taste nicht schnell. Bzw. was ist denn schnell? Ich warte bis der Track anfängt zu spielen und dann drücke ich den Taster.
`TonUINO Version 2.1
created by Thorsten Voß and licensed under GNU/GPL.
Information and contribution at https://tonuino.de.

=== loadSettingsFromFlash()
Version: 1
Maximal Volume: 25
Minimal Volume: 5
Initial Volume: 15
EQ: 1
Locked: 0
Sleep Timer: 0
Inverted Volume Buttons: 1
=== setstandbyTimer()
0
Firmware Version: 0x92 = v2.0
=== playShortCut()
3
=== disablestandby()
38 Dateien in Ordner 17
Einzel Modus -> eine Datei aus dem Odrdner abspielen
=== disablestandby()
=== nextTrack()
Einzel Modus aktiv -> Strom sparen
=== setstandbyTimer()
0
Card UID: D9 A0 76 48
PICC type: MIFARE 1KB
Authenticating Classic using key A...
Reading data from block 4 ...
Data on Card :
13 37 B3 47 02 1D 03 00 00 00 00 00 00 00 00 00

=== disablestandby()
70 Dateien in Ordner 29
Party Modus -> Ordner in zufälliger Reihenfolge wiedergeben
Queue :
1
10
25
12
59
7
40
27
52
18
62
39
23
45
57
64
34
58
4
19
31
9
14
35
36
2
70
63
13
44
60
46
37
3
5
47
55
54
48
22
67
49
24
17
69
8
56
53
61
66
68
51
65
26
20
15
21
11
38
43
33
42
29
32
16
30
6
41
28
50
=== nextTrack()
Party -> weiter in der Queue 10
=== nextTrack()
Party -> weiter in der Queue 25
=== nextTrack()
Party -> weiter in der Queue 12
=== nextTrack()
Party -> weiter in der Queue 59

Com Error 6
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
=== playShortCut()
1
Shortcut not configured!
`

**Comment by Strandbummler** [comment]
Kurze Ergänzung: Es passiert auch von selber. Ich habe nicht einen Button gedrückt und nach ein paar Songs hat er einfach aufgehört zu spielen.

**Comment by xfjx** [comment]
Hast du eventuell Lücken in der Nummerierung?

**Comment by xfjx** [comment]
Sind es immer die selben Nummern?

**Comment by Strandbummler** [comment]
Keine Lücken und kein erkennbares Muster leider. Ich kodiere die MP3s jetzt nochmal alle auf eine niedrigere Bitrate um zu schauen ob es vlt daran liegen könnte. Allerdings habe ich das nur im Party Modus. In allen anderen Modi funktioniert es einwandfrei. Gibt es eine Bitrate bei den MP3s die der DFPlayer maximal schafft?

**Comment by Strandbummler** [comment]
Ok, also, ich hab jetzt alle MP3s noch mal recodiert und den Ordner komplett gelöscht. Dann Ordner neuangelegt, MP3s wieder rein und jetzt funktioniert es. Hmm, sehr seltsam. Irgendwas war mit den Dateien, dass er da plötzlich 15 mehr gefunden hat als da waren. Leider kann ich das nicht nachvollziehen.

**Comment by seisfeld** [comment]
Benutzt du einen Mac? Waren dann evtl. Apple double files. Fangen mit „._„ an und bringen den Player aus dem Tritt.

**Comment by Strandbummler** [comment]
Ne. Ich hab das natürlich extra gecheckt. Doppelt und dreifach. Und es war auch nur in diesem Ordner so. Ich hab auch in der Shell gecheckt ob sich in dem Ordner noch irgendwelche Leichen verbergen. Na ja. Sehr ominös. Wenn es nicht gegen das Copyright verstoßen würde, würde ich die Dateien mal zur Verfügung stellen. Ich denke wir können hier zu machen.
