### ISSUE TITLE
sys |    tracks: mp3 | error code 255

### ISSUE THREAD

**Issue by jenshackel** [xfjx/TonUINO#3]
Beim Start der Firmware aus dem  Communitiyordner "Seisfeld" erscheint im Terminal die Meldung:

sys |    tracks: mp3 | error code 255
65520

Es werden keine Audiodateien abgespielt. Mir ist nicht klar ob es sich um einen Fehler im Programm oder (vermutlich wahrscheinlicher) in der Datei Struktur der SD Karte handelt.

**Comment by seisfeld** [comment]
Er sollte da eigentlich anzeigen wieviele Tracks er auf der Karte gefunden hat. Hier scheinbar keine Ausgabe. Das Problem ist vermutlich Zeile 97+98:

`const uint8_t softwareSerialTxPin = 2;              // software serial tx, wired with 1k ohm to rx pin of DFPlayer Mini`
`const uint8_t softwareSerialRxPin = 3;              // software serial rx, wired straight to tx pin of DFPlayer Mini`

Und daher keine Kommunikation zwischen Arduino und DFPlayer Mini.

Tausche da mal die 2 und die 3. Die Version ist direkt von meine Dev Board, was RX und TX anders belegt hat...

**Comment by seisfeld** [comment]
Ich habe das mal getauscht, so sollte es 1:1 mit der Platine laufen. Die MP3s für die Dialoge sind natürlich trotzdem anzupassen.

fixed in c1f5877

**Comment by jenshackel** [comment]
Hallo Stephan!
Super, läuft jetzt bestens! Danke für Deine schnelle Hilfe!

**Comment by seisfeld** [comment]
Keine Ursache und freut mich das es gefällt. Es war blöd, dass das nicht _drop in_ kompatibel war.
