### ISSUE TITLE
per knopfdruck zu nächstem oder vorherigem Ordner springen

### ISSUE THREAD

**Issue by 3rdlvlspprt** [xfjx/TonUINO#41]
Gibt es die Möglichkeit per knopfdruck zu nächstem oder vorherigem Ordner springen? Bzw, könnte das eingebaut werden? So könnte man Karten sparen, und z.B. die Ordner 10, 20,30,40 per Karte ansteuern, und die Ordner 10,11,12,13,14 etc. dann per Knopfdruck.

**Comment by seisfeld** [comment]
Nein die Möglichkeit gibt es nicht.

**Comment by 3rdlvlspprt** [comment]
Gäbe es denn die Möglichkeit das zu programmieren?

**Comment by seisfeld** [comment]
Du kannst Wünsche natürlich gerne [hier](http://discourse.voss.earth/t/features-fuer-die-naechste-software-version/16) äussern. Am besten ist aber, du baust es für dich selber ein. Das geht schon ziemlich gegen unser Bedienkonzept... Wir sind halt an dem Punkt wo wir eine Recht große Userbase haben und einfach nich ALLES machen können und wollen.
