### ISSUE TITLE
Dev playshortcuts 3, geht nicht nach upload

### ISSUE THREAD

**Issue by 3rdlvlspprt** [xfjx/TonUINO#44]
Der shortcut 3 funktioniert erst, nachdem man ihn per Menü zugewiesen hat. Ansonsten kommt shortcut not configured. Aber, man kann ja Ordner vorher schon zuweisen, indem man bei shortcut 3 die Null entfernt, trotzdem geht es nicht. Erst nach Zuweisung per Menü.

Ist das so gewollt?

**Comment by 3rdlvlspprt** [comment]
Interessiert das überhaupt jemanden?

**Comment by seisfeld** [comment]
Alle Shortcuts funktionieren erst wenn man sie zugewiesen hat - weil sie per default eben nicht gesetzt sind. Das ist so gewollt, ja. Deswegen kommt auch die Meldung am Anfang.

> Aber, man kann ja Ordner vorher schon zuweisen, indem man bei shortcut 3 die Null entfernt, trotzdem geht es nicht.

Falls du damit meinst, in der Firmware den default Wert zu verändern: Das setzten der defaults geschieht nur einmal ganz zu Anfang auf einem ganz jungfreulichen Arduino und wird dann im eeprom gespeichert. Danach kannst du da ändern was du willst, solange du nicht im Menü ein Reset der Einstellungen vornimmst, wird diese Änderung nicht übernommen. Auch das ist gewollt.

**Comment by 3rdlvlspprt** [comment]
Und warum kann man dann in der Firmware, vor dem hochladen, Ordner zuweisen? Das macht doch dann gar keinen Sinn, wenn man die erst per Menü zuweisen muss.

**Comment by seisfeld** [comment]
Man kann (und soll) in der Firmware vor dem hochladen keine Ordner zuweisen. Woher nimmst du diese Information? Die Daten dort sind um die Settings initial ins eeprom zu schreiben. Diese werden dann bei jedem einschalten ausgelesen. Verändert werden diese Daten über das Adminmenü.
