### ISSUE TITLE
Reise nach Jerusalem

### ISSUE THREAD

**Issue by Dakkaron** [xfjx/TonUINO#49]
Ich finde die Idee mit dem Stoptanz genial. Wäre es möglich, auch das Spiel "Reise nach Jerusalem" zu implementieren (https://de.wikipedia.org/wiki/Reise_nach_Jerusalem)?

Da müsste wie beim Stoptanz das Playback zufällig pausiert werden (allerdings mit einer höheren Mindestzeit zwischen Pausen, vielleicht 15 sec) und pausieren bis der Spielleiter das Playback wieder weiter schaltet, z.B. über einen Druck auf Play oder durch eine Karte.

**Comment by seisfeld** [comment]
GitHub Issues sind nicht für Feature Wünsche/Anregungen gedacht. Stattdessen gerne in der [Community](https://discourse.voss.earth) anmelden und dort diskutieren.
