### ISSUE TITLE
Box spielt weiter obwohl Karte weg

### ISSUE THREAD

**Issue by CTSchorsch** [xfjx/TonUINO#52]
Hallo,
ich habe die Box im Modus "Karte weg=Pause" eingestellt. So weit klappt da alles. Allerdings spielt die Box auch ohne Karte weiter, wenn man ein Lied weiter drückt....

Kling für mich jetzt nach nicht gewünscht. Wo kann ich so Bugs melden ?

Gruß
Georg

**Comment by seisfeld** [comment]
Bist du sicher, daß du im richtigen repo bist!? Die 

> Wo kann ich so Bugs melden ?

Am besten an der Quelle der Firmware. ;)

Ansonsten ist die Chance sehr groß das sich der Author des Forks in der [TonUINO Community](https://discourse.voss.earth) aufhält. Nen Namen solltest du aber schon haben.

**Comment by CTSchorsch** [comment]
Tja, dann anscheinend nicht :) Ich habe gedacht die DEV Version der original Firmware zu haben. 
ich schreibe es ins Forum
Danke
Georg
