### ISSUE TITLE
Com Error 6

### ISSUE THREAD

**Issue by mrguybrush** [xfjx/TonUINO#6]
Ich bekomme leider immer einen Com Error 6 angezeigt. Ich kann auch keine Karte beschreiben. Wo könnte der Fehler liegen? 
Wäre es eigentlich möglich noch eine alte Version der Firmware zu bekommen? Würde gerne Chips/Tokens anstatt der Karten benutzen. Auf denen lassen sich jedoch leider keine Infos speichern. Das müsste dann im Eprom (wie in der alten Version) geschehen. 

Kleiner Auszug aus der seriellen Ausgabe:
Card UID: D3 03 0D 03
PICC type: MIFARE 1KB
Authenticating using key A...
Current data in sector:
   1      7   00 00 00 00  00 00 FF 07  80 69 FF FF  FF FF FF FF  [ 0 0 1 ] 
          6   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          5   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 
          4   00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  [ 0 0 0 ] 

Reading data from block 4 ...
Data in block 4:
 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00

Neue Karte konfigurierenTrack beendet251
Track beendet1

Com Error 6
Track beendet1

Com Error 6
Track beendet2

Com Error 6
Track beendet3

Com Error 6
Track beendet4

Viele Grüße!!
Julian

**Comment by xfjx** [comment]
Hallo Julian,

woher hast du den DFPlayer? Ich glaube den Fehler hatte ich mal bei einem mit fehlerhafter Firmware.

Was steht unten auf dem Chip?

**Comment by HeikoGr** [comment]
1=nicht bereit, 2=Sleepmode, 3=Fehler RS232, 4K=Checksumerror, 5=ungültige Dateinummer, 6=Datei nicht gefunden, 7=Inter-cut error, 8=SD-Card error, 10=in Sleepmode

Quelle: https://bascomforum.de/lexicon/index.php?entry/93-dfplayer-mini/


Hast du den mp3 Ordner auf die SD Karte kopiert?

**Comment by mrguybrush** [comment]
![20181008_154058](https://user-images.githubusercontent.com/4942933/46612557-32aed000-cb11-11e8-9d0c-8a973881ddb5.jpg)
![20181008_154116](https://user-images.githubusercontent.com/4942933/46612558-32aed000-cb11-11e8-83ef-cf1d5215a3d0.jpg)

den Ordner mp3 und advert habe ich kopiert... dazu noch 2 ordner (01, 02) mit jeweils einer mp3 drin (kurze Dateinamen ohne Umlaute)

das MP3 Modul funktioniert auch für die Ansagen...

**Comment by mrguybrush** [comment]
auf dem Cip steht MH-ETLIVE  MH 2024k-24ss

**Comment by xfjx** [comment]
OK von denen ist mir nichts bekannt.

Versuch bitte mal die SD Karte neu zu formatieren und die Ordner neu drauf zu kopieren. Achte bitte (falls macOS im Spiel ist) darauf dass keine Dotfiles angelegt werden (auch kein .Trash oder Spotlight ...) am besten Linux nehmen ;)

**Comment by mrguybrush** [comment]
ok... stört der windows system value information  ordner?

**Comment by seisfeld** [comment]
Wie genau sind die Dateinamen in 01 und 02? "kurz und ohne Umlaute" nutzt nix wenn vorne nicht die Nummer steht. Also `001foo.mp3`, `002bar.mp3` usw. gehen - `test1.mp3`, `test2.mp3`gehen nicht.

**Comment by mrguybrush** [comment]
den mp3 ordner lasse ich unangetastet. und lege dann die Hörspiele in ordner 01 oder 02

**Comment by mrguybrush** [comment]
bekomme jetzt auch ein MIFARE_Write() failed: A MIFARE PICC responded with NAK. wenn ich die karte beschreiben möchte :(

**Comment by mrguybrush** [comment]
achso benutze übrigens Windows (ich weiß, bah! :D)

**Comment by mrguybrush** [comment]
müssen die Hörspiel mp3s speziell benannt werden?

**Comment by HeikoGr** [comment]
Ja
001.mp3
002.mp3
...

Wobei die dateinamen auch noch länger sein dürfen. Wichtig ist, dass die ersten drei Zeichen fortlaufend nummeriert sind

**Comment by xfjx** [comment]
Die alter Version kannst per Git bekommen. Aber da fehlen noch viele Sachen und die Audio Dateien sind auch nicht zur 2.0 kompatibel.

https://github.com/xfjx/TonUINO/tree/ff2a169f698908e88877cc806f930d24fd27fb59
