### ISSUE TITLE
Can not select an arbitrary file for shortcut(3)/Einzelmodus

### ISSUE THREAD

**Issue by dl9sec** [xfjx/TonUINO#63]
Hi,

I want to have the welcome melody (shortcut(3) in "Einzelmodus") at folder 99, named 255.mp3.
This is the one and only file in that folder. unfortunately I can not select it. The announcement stucks at 1, incrementing doesn't work.

Is this the wanted behaviour? Must there be 253 files exist before?

Thanks in advance.

Regards, Thorsten

**Comment by seisfeld** [comment]
> Is this the wanted behaviour? Must there be 253 files exist before?

Yes, as per the FAQs, there are not gaps allowed in naming the files.

**Comment by dl9sec** [comment]
Tnx. Can you point me to that FAQ? Read a lot of FAQs of the TonUINO, but couldn't find that one...

**Comment by seisfeld** [comment]
[Hardware FAQ](https://discourse.voss.earth/t/faq-kategorie-hardware/926)
[Software FAQ](https://discourse.voss.earth/t/faq-kategorie-software/924)
