### ISSUE TITLE
10 Sekunden bis „Karte“ abgespielt wird

### ISSUE THREAD

**Issue by LennartHennigs** [xfjx/TonUINO#65]
Hi, 
Ich habe gerade eine neue Box mit der aktuellen Firmware bestückt. Beim Testen ist mir aufgefallen, dass die Box gut 10 sec. braucht bis sie Lieder spielt. 
Eine ältere Box (mit FW 1.x) hatte das nicht. Da ging es ja sofort los. 
Hast Du eine Idee woran das liegen könnte?

VG
Lennart

**Comment by seisfeld** [comment]
An der Firmware liegt das nicht. Ausführliches Troubleshooting (in Richtung Verkabelung, TX Pin des DFPlayer hat GND Kontakt etc.) führt jetzt hier zu weit. Du bist ja auch in der Community aktiv, ich schlage vor du verlagerst die Diskussion nach dort.

Als Einstieg bietet sich die Hardware FAQ an. Dort gibt es unter _Der DFPlayer „macht nichts“, überspringt Tracks oder ähnliches._ als letzten Punkt Hinwiese die dein Problem u.U. schon lösen könnten.

**Comment by LennartHennigs** [comment]
Hey Stwphan,
danke fur die schnelle Antwort!
Ok, dann schaue ich mal in der Community nach den Ursachen. 
Thx. 

Viele Grüße 
Lennart
