### ISSUE TITLE
Software fork for CubieKid

### ISSUE THREAD

**Issue by jenshackel** [xfjx/TonUINO#7]
Hallo Stephan,
ich arbeite gerade an einem Gehäuse [https://github.com/jenshackel/CubieKid](https://github.com/jenshackel/CubieKid) nebst angepasster TonUINO Hardware. Ich möchte gerne als Basis eine modifizierte Version deiner Software (IR-Funktion entfernt dafür Batterieüberwachung und Auto-Power-Off hinzugefügt) verwenden. Die ist deutlich übersichtlicher und besser dokumentiert als das Original, finde ich.

Mein CubieKid Projekt hat eine andere Lizensierung (CreativeCommons). Wie hättest Du gerne die Angaben für Copyrights und Lizenz deiner Software angegeben?

Vielleicht am besten per E-Mail weiter besprechen? db3jhf (at) darc.de

Viele Grüße,
Jens

**Comment by xfjx** [comment]
melde mich per mail bei dir
