### ISSUE TITLE
Hörspielmodus neuer Track

### ISSUE THREAD

**Issue by skss83** [xfjx/TonUINO#8]
So wie ich es sehe, kann man im Hörspielmodus nicht einen anderen Track auswählen. Die Weitertaste hat die gleiche Funktion wie die Pause-Taste.
Muss/kann ich den Code so ändern, um ein anderen Track zu wählen?
Anstatt:

> `
  if (myCard.mode == 1) {
    Serial.println(F("Hörspielmodus ist aktiv -> Strom sparen"));
    mp3.sleep();`

Änderung:
`
  if (myCard.mode == 1) {
track = random(1, numTracksInFolder + 1);
    Serial.println(F("Hörspielmodus ist aktiv -> zufälligen Track spielen:"));
    Serial.println(track);
    mp3.playFolderTrack(myCard.folder, track);
  }
`

**Comment by seisfeld** [comment]
Also der Hörspielmodus spielt ja absichtlich nur einen zufälligen Titel und stoppt dann. Wenn du möchtest, dass danach ein weiterer (zufälliger) Titel abgespielt wird, verwende den Partymodus. Oder den Albummodus, der spielt sequenziell den gesamten Ordner.

**Comment by skss83** [comment]
Nein, falsch verstanden. Ich kann kein Track weiter machen, weil die Weiter-taste die gleiche Funktion wie die Pause Taste hat. Das heißt ich kann nicht ein anderes Hörspiel auswählen.

**Comment by seisfeld** [comment]
Das das habe ich schon verstanden. Aber: Im Höspielmodus sollte es gar keine Weiter-Taste geben. Weder für weiter noch für Pause (wenn die Taste da Pause macht, ist das ein Fehler). Der Modus ist explizit dafür gemacht, dass nachdem die Karte gelesen wurde genau EIN zufälliger Track abgespielt wird und danach wird gestoppt.

**Comment by skss83** [comment]
Ja richtig. Aber wenn du ein anderes Hörspiel als das vom tonuino ausgewählte hören willst, benötigst du eine weiter Taste. Oder man muss die Karte nochmal auflegen...
Es geht nicht darum ein zweites/nachfolgendes zu hören, sondern ein anderes

**Comment by seisfeld** [comment]
Genau, in dem Fall muss man in der aktuellen Implementierung die Karte erneut auflegen. Was vermutlich für Kinder auch einfacher ist als irgendwelche Tasten zu drücken. Aber danke für die Anregung. 👍 Wir behalten das mal im Auge. :)
