### ISSUE TITLE
Unterstützung für RFID RDM6300

### ISSUE THREAD

**Issue by hankman13** [xfjx/TonUINO#9]
Hallo Thorsten,

sehr starkes Projekt. Ich hatte mich selbst an so einem Projekt mal versucht, aber bin an der Logik nicht weiter gekommen ([Arduino RFID Jukebox](https://github.com/hankman13/Arduino-RFID-Jukebox/blob/master/src/main.cpp).
Derzeit habe ich mir eine [Phoniebox](https://github.com/MiczFlor/RPi-Jukebox-RFID) gebastelt, bin damit zufrieden bis auf die Tatsache, dass ein RPi einen höheren Stromverbrauch hat und ein plötzliches ausschalten ungünstig sein kann.

Da ich für die Phoniebox andere RFID Karten nutze (125 kHz) als du (13.56 MHz), wollte ich fragen ob es möglich ist eine Unterstützung für das RDM6300 Modul einzubauen?

Ich freue mich auf deine Antwort!

**Comment by xfjx** [comment]
Hallo Hankman,

das entsprechende Modul liegt mir nicht vor daher müsste ich mir dies erstmal bestellen und es scheint keine fertige Bibliothek für die Nutzung mit dem Arduino zu geben. Ich finde jedenfalls keinen Hinweis dazu und generell nichts dazu ob das Modul die Tags überhaupt beschreiben kann. Scheinbar sind auch die meisten 125 kHz Tags meist read only bzw können maximal mit einer ID beschrieben werden. Wäre dann die Frage ob der Payload für die Konfiguration der Tags in diesen Speicherplatz passen würde. Ich denke mal eher das wird nichts. Gerne kannst du selbst versuchen ob du es in meinen Code eingebaut bekommst und mir einen Pull Request schicken. Bitte denk aber daran dass ein solches Feature dann konfigurierbar sein muss und man zwischen beiden Modulen wählen können müsste. Auch das klingt nach sehr viel Komplexität ohne wirklich großen Nutzen.

Grundsätzlich wäre aber die einfachste Lösung für dein Problem auf das bereits unterstützte Modul zu wechseln - Es kostet nur ein paar Euro.

**Comment by hankman13** [comment]
Hi Thorsten,

ich hab nochmal nach einer Bibliothek gesucht, finde aber auch nur Beispiele für das Lesen. Auch die Karten scheinen nicht immer lesen und schreiben zu Unterstützen. Ich hab mir schon ein Modul bestellt und freue mich auf das Basteln.

Danke!
