### ISSUE TITLE
website should work without allowing google

### ISSUE THREAD

**Issue by c33s** [xfjx/TonUINO#98]
![image](https://user-images.githubusercontent.com/649209/120076773-9661df00-c0a7-11eb-945a-33eeab93a6c1.png)

currently the website https://tonuino.de/ is not usable if google fonts is not allowed. could be easily solved by adding link tags to the icon text
```
<dt><a href="https://voss.earth/tonuino"><i class="fas fa-file-alt fa-5x"></i></a></dt>
<dd>Anleitung</dd>
```
->
```
<dt><a href="https://voss.earth/tonuino"><i class="fas fa-file-alt fa-5x"></i></a></dt>
<dd><a href="https://voss.earth/tonuino">Anleitung</a></dd>
```

as google uses this domain for tracking it could also be a possible problem with the DSGVO

**Comment by xfjx** [comment]
Hi, I did the changes. Thanks for pointing that out.
